var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "    x   xxx x x xxx x    xx                                                     ",
   "    x   x   x x x   x     x                                                     ",
   "    x   xx  x x xx  x     x                                                     ",
   "    x   x   x x x   x     x                                                     ",
   "    xxx xxx  x  xxx xxx  xxx                                                    ",
   "                                                                                ",
   "                                    oo                                          ",
   "                                   xxxx                                         ",
   "                                           xxx                                  ",
   "                                                  x                          x  ",
   "  x                                                    xxx                   x  ",
   "  x                                                            xx            x  ",
   "  x                                                                          x  ",
   "  x                            xxx   xxx   xxx   xx    x          xxx     o  x  ",
   "  x  @    o                                                       xxxxx      x  ",
   "!!xxxxxxxxxxxx   xxxxxxxxxxxxxx                            xxxxxxx!x!xxxxxxxxx!!",
   "!!xxxxxxxxxxxx   xxxxxxxxxxxxxx                            xxxxxxx!x!xxxxxxxxx!!",
   "!!xxxxxxxxxxxx!!!xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx!xxxxx!xxxxxxx!!",
   "!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx!!!!!xxxxxxxx!!",
   "!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                  x!x         x!!!!!!x            ",
   "                                                                                  x!x         x!xxxx!x            ",
   "                                                                                  x!x         x!x  x!x            ",
   "                                                                                  xvx         xvx  xvx            ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                             o    ",
   "                                                                             x       xxxxx  xx   xx   xx    xxx   ",
   "                                                                             x           x                        ",
   "                                                                             xx          x                        ",
   "     @                                                                       x           x                        ",
   "    xxx        o     o                                                       x           x                        ",
   "    x x      xxxxxxxxxxx       xxx      xx                                   xxx         x                        ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!x      x!!!!!!!!!!!!!!!!!!!!!x           x!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!xxxxxxxxxxxx      xxxxxxxxx!!!!!!!!!!!!!x           x!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!x                        ox!!!!!!!!!!!!!xxxx      xxx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!x                        ox!!!!!!!!!!!!!x           x!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!xxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           x!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!x                                                xxxx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!x                          o                        x!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!x                                                   x!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!xxxxxxxxxxxx =       x     =      x       = xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                                                                                                                                                      ",
   "                                                                                                                                                                                             ",
   "*                                                                                                                                                                                            ",
   "*                                                                                                                                                                                            ",
   "*                                                                                                                                                                                            ",
   "*                                                                                                              o                 o                                                           ",
   "*                                                                                                                                                   xxxxxxx    x                             ",
   "*                                                                                                                                          xxxxxxx             x                             ",
   "*                                                                                                         xxx      xxx      xxx      xxx                       x      o                      ",
   "*                                                                                             o       x                                                        x                             ",
   "*                                                    o                       xxxx    xxxx   xxxxx                                                              x                             ",
   "*                                                 xxxxxxx                                                                                                      x                             ",
   "*                                                             xxxxx     xxxx                                                                                   x                             ",
   "*                                     xxxxxxxx                                                                                                                 x                             ",
   "*           @                                                                                                                                                  x                             ",
   "*                                x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxx!!!!xxx!xx!xx!xxx!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxx!xx!xxx!xx!xx!!xx!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxx!!!xxxx!xx!xx!x!x!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxx!xx!xxx!xx!xx!xx!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxx!xxx!xxx!!xxx!xxx!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                           xx           xx              xx                                    ",
   "                                                                                                              ",
   "                                 o                           v       v                                        ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                           ooo                ",
   "                                           ||           ||              ||             ooooooooooo            ",
   "             xxxxxxxxxxxxxxxxxxxxxxxx      xx     x     xx      x       xx      x     xxxxxxxxxxxxx           ",
   "                                                                                                              ",
   "       x                                                                                                      ",
   "        x                                                                                                     ",
   "         x                                                                                                    ",
   "          x             o                                                                                     ",
   "                                                             x       x                                        ",
   "              x                                                                                               ",
   "                  xx     x     x                                                                              ",
   "                                                                                                              ",
   "                                     x                                                                        ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                  x                                                                           ",
   "                           xx                                                                                 ",
   "     @                                                                                                        ",
   "  xxxxxxx     xx     xx                                                                                       ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
